#!/usr/bin/env bash
# Remove project-local files generated by dependency installation.
#
# The overlay skill directories (.agents/skills, .claude/skills) are committed
# to the repo and are NOT generated artifacts, so clean must never prune them.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

node <<'NODE'
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = process.cwd();

function removePath(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

removePath(path.join(repoRoot, "node_modules"));

for (const entry of fs.readdirSync(repoRoot, { withFileTypes: true })) {
  if (entry.name === ".skills-install.lock" || /^\.skills-install\.lock\..*\.tmp$/.test(entry.name)) {
    removePath(path.join(repoRoot, entry.name));
  }
}
NODE

echo "clean: removed generated dependency install files"
